### ISSUE TITLE
buoy data

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/cdm_reader_mapper#13]
* Enhance workflow for netcdf buoy data 
* ask @aanderss for test data

**Comment by aanderss** [comment]
C-RAID buoy data and documentation is available here:
https://www.seanoe.org/data/00660/77184/

First steps:
1.  create mapping from C-RAID variables to CDM 
2. identify missing information / variables

**Comment by ludwiglierhammer** [comment]
[Here](https://github.com/glamod/cdm-testdata/tree/buoy_tests/c_raid/cdm_tables) you can find C-RAID CDM test header and observations tables.

**Comment by ludwiglierhammer** [comment]
@aanderss, are you happy with this [testing results](https://github.com/glamod/cdm-testdata/tree/buoy_tests/c_raid/output) and [CDM tables](https://github.com/glamod/cdm-testdata/tree/buoy_tests/c_raid/cdm_tables)?
If so you could merge both this data into the [cdm-testdata main branch](https://github.com/glamod/cdm-testdata/tree/buoy_tests) and PR #28 into [cdm_reader_mapper main branch](https://github.com/glamod/cdm_reader_mapper).
[Here]() you can find the corresponding [CDM mapper tables](https://github.com/ludwiglierhammer/cdm_reader_mapper/tree/buoys_mapper/cdm_reader_mapper/cdm_mapper/tables/c_raid). 
It took the information from the [C-RAID_CDM-tables.xlsx](https://github.com/glamod/cdm_reader_mapper/files/14978858/C-RAID_CDM-tables.xlsx) we work out together.

**Comment by ludwiglierhammer** [comment]
I took `<PARAM>_ADJUSTED` for `quality_flag` and `original_value`:

```
  "quality_flag": {
    "sections": "drifter_measurements",
    "elements": "SST_ADJUSTED_QC",
    "code_table": "qc_flag"
  },
...
  "original_value": {
    "sections": "drifter_measurements",
    "elements": "SST_ADJUSTED",
    "decimal_places": "decimal_places"
  },
```

**Comment by ludwiglierhammer** [comment]
#28 is merged into the main branch
@aanderss: I took [new C-RAID TESTING data](https://github.com/glamod/cdm-testdata/tree/main/c_raid). It is data from 2004-12-20 and contains both SST and ATMS values.
