### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/cdm_reader_mapper#17]
### Goal
make a ``cdm_reader_mapper``  release on  [pypi](https://pypi.org/)

### Questions

* author list: 
    * is the current list ok? 
    * is anybody missing? 

* is the curent MIT license ok?
* who could answer those questions?
* may help: @aanderss, @jtsiddons 

### Notes

* author list:
    * [mdf_reader documentation](https://github.com/glamod/mdf_reader/blob/backup/docs/index.rst): David Berry, Irene Perez Gonzalez and Beatriz Recinos
    * [cdm_mapper documentation](https://github.com/glamod/cdm-mapper/blob/master/docs/index.rst): David Berry, Irene Perez Gonzalez and Beatriz Recinos

**Comment by rcornes** [comment]
- Author list and Acknowledgements: looks good to me
- License: we tend to favour the CC-BY-4.0 licence for our code
- Github A/C: @rcornes

**Comment by ludwiglierhammer** [comment]
@rcornes: Thanks for the information :sunny:
@aanderss: Is license [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode.en) also ok for us? If so, I would change the [glamod-marine-processing license](https://github.com/glamod/glamod-marine-processing/blob/master/LICENSE) in the same way.

**Comment by ludwiglierhammer** [comment]
@rcornes, @aanderss: regarding the licensing issue:

I found an [interesting discussion](https://github.com/github/choosealicense.com/issues/33) about Creative Commons Licenses and GitHub. As far as I understand it [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode.en) is for not open-source publication (no guarantee on my part). Perhaps the [GNU GPL v3.0](https://www.gnu.org/licenses/gpl-3.0.en.html)  license is the closest to CC-BY 4.0?

At the moment, GitHub does not offer CC-BY-4.0 license, but GNU GPL v3.0. Instead, [here](https://github.com/ludwiglierhammer/cdm_reader_mapper/community/license/new?branch=pypi_release) are the current provided licenses. Of course, we can simply add CC-BY-4.0 as our license but then it is not one of the "official" ones. 

What is your opinion about this?

**Edit**:
We can use two licenses (e.g.):
* MIT or GNU GPL v3.0 for the pypi release
* CC-BY-4.0 for the zenodo DOI (this is the default one)

I have no idea what two licenses exactly mean.

**Comment by aanderss** [comment]
@rcornes , @ludwiglierhammer 
I can confirm Ludwig's findings regarding the CC license. CC does not recommend to use Creative Commons licenses for software. See the FAQ here: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

I would prefer to choose either MIT or GPL for the code and the release on zenodo. CC appears to be appropriate for documentation etc.. 

@ludwiglierhammer: Does GPL v3.0 pass the license checker?

**Comment by ludwiglierhammer** [comment]
@rcornes, @aanderss 
Unfortunately, license scan failed with GNU GPL v3.0.

[![FOSSA Status](https://app.fossa.com/api/projects/git%2Bgithub.com%2Fludwiglierhammer%2Fcdm_reader_mapper.svg?type=large&issueType=license)](https://app.fossa.com/projects/git%2Bgithub.com%2Fludwiglierhammer%2Fcdm_reader_mapper?ref=badge_large&issueType=license)

```
These packages contain code files that may require you to disclose your source code under a compatible license, 
unless they’re distributed and run as completely separate processes & packages.
```

**Comment by ludwiglierhammer** [comment]
If you do not want to use MIT license, is [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html) an option.
It is used by [xclim](https://github.com/Ouranosinc/xclim?tab=Apache-2.0-1-ov-file) and [xarray](https://github.com/pydata/xarray?tab=Apache-2.0-1-ov-file).

**Comment by aanderss** [comment]
Apache License 2.0 is used by other ECMWF software such as [ecCodes](https://confluence.ecmwf.int/display/ECC/License).
So I recommend using this license - requesting confirmation from project lead.

**Comment by rcornes** [comment]
Happy to go with what you/C3S decide on this.

**Comment by ludwiglierhammer** [comment]
We use Apache v2.0 license not. See PR #69.

**Comment by ludwiglierhammer** [comment]
Published: https://pypi.python.org/pypi/cdm_reader_mapper
