### ISSUE TITLE
zenodo release

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/cdm_reader_mapper#18]
### Goal
make a ``cdm_reader_mapper``  release on  [zenodo](https://zenodo.org/) and assign a DOI.

### Requirements

Firstly, publish ``cdm_reader_mapper`` on pypi (#17 )

**Comment by ludwiglierhammer** [comment]
Hi @aanderss, @TinaLeiding, @rcornes, @jtsiddons, @lizkent,
feel free to send me your ORCID iD's for the DOI

**Comment by ludwiglierhammer** [comment]
This is a file containing information for the DOI: https://github.com/ludwiglierhammer/cdm_reader_mapper/blob/zenodo_release/.zenodo.json

@aanderss, @TinaLeiding, @rcornes, @jtsiddons, @lizkent please add som comments etc:

"title": "cdm_reader_mapper: Common Data Model reader and mapper toolbox"
  "keywords": [
    "observations",
    "ship",
    "buoys",
    "climatology",
    "climate change",
  ],
"license": "MIT", -> we discuss in #17

**Comment by aanderss** [comment]
proposed description text (extracted from [README](https://github.com/ludwiglierhammer/cdm_reader_mapper/blob/pypi_release/README.rst):

The cdm_reader_mapper toolbox is a [python](https://www.python.org/) tool designed for both:
    to read data files compliant with a user specified [data model](https://cds.climate.copernicus.eu/toolbox/doc/how-to/15_how_to_understand_the_common_data_model/15_how_to_understand_the_common_data_model.html)
    map observed variables and its associated metadata from a [`](https://github.com/ludwiglierhammer/cdm_reader_mapper/blob/pypi_release/README.rst#id1)data model`_or models combination to the [C3S CDS Common Data Model](https://git.noc.ac.uk/brecinosrivas/cdm-mapper/-/blob/master/docs/cdm_latest.pdf) (CDM) format

cdm_reader_mapper development is funded through Copernicus Climate Change Service [C3S](https://climate.copernicus.eu/). Furthermore, acknowledgments go to National Oceaography Centre [NOC](https://noc.ac.uk/) and UK Marine and Climate Advisory Service [UKMCAS](https://www.metoffice.gov.uk/services/data/met-office-marine-data-service).

**Comment by ludwiglierhammer** [comment]
@jtsiddons: do you want me to add your ORCID iD?

**Comment by ludwiglierhammer** [comment]
@rcornes: do you want me to add your ORCID iD?

**Comment by jtsiddons** [comment]
@ludwiglierhammer: https://orcid.org/0009-0003-5558-2327

**Comment by rcornes** [comment]
@ludwiglierhammer: yes please. 

https://orcid.org/0000-0002-7688-4485

**Comment by ludwiglierhammer** [comment]
Add this bagde to ``README.rst`` after publishing on zenodo:

https://img.shields.io/badge/fair--software.eu-%E2%97%8F%20%20%E2%97%8F%20%20%E2%97%8F%20%20%E2%97%8F%20%20%E2%97%8F-green

**Comment by ludwiglierhammer** [comment]
First release: https://zenodo.org/badge/DOI/10.5281/zenodo.13982457.svg
