### ISSUE TITLE
QC mapping

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/cdm_reader_mapper#36]
# QC mapping

We have to think about some reworking of QC mapping:

## GCC IMMT

[Here](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json) is the json fiel containing parameters read with mdf_reader.
[Here](https://github.com/glamod/cdm_reader_mapper/tree/main/cdm_reader_mapper/cdm_mapper/tables/gcc_mapping) are the json files containing the CDM mapping.

### current state

location_quality: **3**
report_quality: **QCI** [quality control indicator](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L324-L328)
quality_flag: **2**

### suggestions

location_quality: **QI20** [QC indicator for ship's position](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L580-L584)
quality_flag (at): **QI6** [QC indicator for air temperature](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L496-L500)
quality_flag (dpt): **QI7** [QC indicator for dew point](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L502-L506)
quality_flag (slp): **QI8** [QC indicator for air pressure](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L508-L512)
quality_flag (sst): **QI10** [QC indicator for sea surface temperature](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L520-L524)
quality_flag (wbt): **QI19** [QC indicator for wet bulb temperature](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L574-L578)
quality_flag (wd): **QI4** [QC indicator for wind direction](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L484-L488)
quality_flag (ws): **QI5** [QC indicator for wind speed](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/gcc_immt.json#L490-L494)

## ICOADS

[Here](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json) is the json fiel containing parameters read with mdf_reader.
[Here](https://github.com/glamod/cdm_reader_mapper/tree/main/cdm_reader_mapper/cdm_mapper/tables/icoads_r3000) are the json files containing the CDM mapping.

### current state

location_quality: **3**
report_quality: **IRF** [intermediate reject flag](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L2236-L2240)
quality_flag: **2**

### suggestions

location_quality: **LZ** [2x2 landlocked flag](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L717-L721) or **QI20** [QC indicator for ship's position](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L1013-L1017) (see gcc_mapping); **Note:** we need LZ for level1e quality control.
quality_flag (at): **QI6** [QC indicator for air temperature](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L929-L933)
quality_flag (dpt): **QI7** [QC indicator for dew point](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L935-L939)
quality_flag (slp): **QI8** [QC indicator for air pressure](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L941-L945)
quality_flag (sst): **QI10** [QC indicator for sea surface temperature](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L953-L957)
quality_flag (wbt): **QI19** [QC indicator for wet bulb temperature](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L1007-L1011)
quality_flag (wd): **QI4** [QC indicator for wind direction](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L917-L921)
quality_flag (ws): **QI5** [QC indicator for wind speed](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1.json#L923-L927)

## C-RAID

[Here](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/c_raid.json) is the json fiel containing parameters read with mdf_reader.
[Here](https://github.com/glamod/cdm_reader_mapper/tree/main/cdm_reader_mapper/cdm_mapper/tables/c_raid) are the json files containing the CDM mapping.

### current state

location_quality: **POSITION_QC** [Quality flag on position](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/c_raid.json#L771-L774)
report_quality: **NULL**
quality_flag (at): **AIR_TEMP_ADJUSTED_QC** [AIR_TEMP_ADJUSTED_QC](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/c_raid.json#L859-L862)
quality_flag (dpt): **NULL**
quality_flag (slp): **ATMS_ADJUSTED_QC** [Quality flag applied on each ATMS_ADJUSTED values](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/c_raid.json#L819-L822)
quality_flag (sst): **SST_ADJUSTED_QC** [Quality flag applied on each SST_ADJUSTED](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/c_raid.json#L889-L892)
quality_flag (wbt): **NULL**
quality_flag (wd): **NULL** 
quality_flag (ws): **NULL**

### suggestions

report_quality: **2** or **END_MISSION_QC** [Quality flag on end mission date, time and location; launch time and location seems correct](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/c_raid.json#L535-L538)

**Comment by ludwiglierhammer** [comment]
@aanderss: What do you think about this QC issue and my suggestions?

**Comment by aanderss** [comment]
Do not change GCC IMMT - leave as it is. This will be used in future releases.

ICOADS: just change location_quality to LZ mapping
quality flags are taken from att5, which is IMMT data and only present for ship observations from VOS GDAC /GCC

C-RAID:
current state looks fine
do not change report quality, leave at default 2 (we may need to discuss, if we map other flags to this value)

**Comment by ludwiglierhammer** [comment]
QC: if report_time_quality == (4 | 5): report_quality = 1

**Comment by ludwiglierhammer** [comment]
@aanderss: I implemented the changes in PR #37 and in the new [cdm-testdata release](https://github.com/glamod/cdm-testdata/releases/tag/v2024.06.03). I think we can close this issue and merge the PR. OK?
