### ISSUE TITLE
additional custom schemas tests in ``mdf_reader``

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/cdm_reader_mapper#47]
As mentioned in #40 we want to add some additonal tests for using custom schemas in ``mdf_reader``.

@jtsiddons: These are the steps for implementing new tests:

1. add your input data to ``cdm-testdata``: similar to https://github.com/glamod/cdm-testdata/tree/main/icoads/r300/d201/input
2. add your expected result data to ``cdm-testdata``: similar to https://github.com/glamod/cdm-testdata/tree/main/icoads/r300/d201/output(I recommend to run ``mdf_reader`` with the input data, check the output and push it to ``cdm-testdata``)
3. Do not forget to run ``make_check_sums.py`` to create MD5 checksums of the new data. and add them to your commit.
4. add input data to the ``cdm_reader_mapper`` test data (e.g. test_custom_schema): see https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/data/__init__.py#L126-L132:
4.1. first entry: date and suffix of the input data: similar to ``1913-11-01_subset.imma``
4.2. second entry: complete name of the data model: similar to ``icoads_r300_d201``
5. add output data to the ``cdm_reader_mapper`` result data (e.g. expected_custom_schema): see https://github.com/glamod/cdm_reader_mapper/blob/main/tests/_results.py#L142-L147
5.1. first entry: see ``4.1``
5.2. second entry: see ``4.2``
6. Add test to [test_cdm.py](https://github.com/glamod/cdm_reader_mapper/blob/main/tests/test_cdm.py); see: https://github.com/glamod/cdm_reader_mapper/blob/main/tests/test_cdm.py#L35

**Comment by ludwiglierhammer** [comment]
Hi @jtsiddons, I restructured the tables of both ``mdf_reader`` and ``cdm_mapper`` in PR #97 and #103 to standardize the inputs. These PR's are already pushed into the main branch and yield some breaking changes:

1. ``mdf_reader``: rename ``c_raid`` to ``craid``, ``gcc_immt`` to ``gcc`` and ``imma1`` to ``icoads``
2. ``cdm_mapper``: rename ``c_raid`` to craid and ``gcc_mapping`` to ``gcc`` 
3. ``metmetpy``: rename ``immt`` to ``gcc`` and ``imma`` to ``icoads``
4. rename ``data_model`` into ``imodel``
5. use standardized input data model names (imodel) with both ``mdf_reader`` and ``cdm_mapper``: e.g. ``icoads_r300_d701``
```
from cdm_reader_mapper.mdf_reader import read
from cdm_reader_mapper-cdm_mapper import map_model

imodel = ""icoads_r300_d704"
read_ = read("icoads_r300_d701_1845-04-01_subset.imma", imodel=imodel) 
cdm_tables = map_model(read_.data, imodel=imodel)
```
6. NRT data is now in ``icoads_r302``

I added the changes in the above explanation how to custom schemas test.

Could you please start a PR which adjusts the example notebooks. This would be a great help

Thanks!

**Comment by jtsiddons** [comment]
@ludwiglierhammer: I'll look at the example notebooks this week and sort a PR for you. Thanks for the updates!

**Comment by jtsiddons** [comment]
@ludwiglierhammer: see #105

**Comment by ludwiglierhammer** [comment]
#105 is merged

**Comment by ludwiglierhammer** [comment]
In #111 I added some tests for both external schema and code table paths. In the testing suite, I just took the paths to the already implemented tables as external paths. Now, we can set ext_schema_path and ext_table_path independently of each other.

```
read_ = mdf_reader.read(
    ...,
   ext_schema_path=<external_schema_path>,
   ext_table_path=<external_code_table_path>,
)
``` 
**Note:** The external schema file's name has to be the last directorie's name of the external schema path plus the suffix ``.json``.

e.g. 
ext_schema_path=d(1)/../d(n-1)/icoads
File naming is icoads.json

In addition, one can also set external schema file:

```
read_  mdf_reader.read(
    ...,
    ext_schema_file=<external_schema_file>,
)
```

@jtsiddons: May I ask you again to adjust the [CLIWOC_datamodel notebook](https://github.com/glamod/cdm_reader_mapper/blob/main/docs/example_notebooks/CLIWOC_datamodel.ipynb)?  I think the others should be fine.

**Comment by ludwiglierhammer** [comment]
@jtsiddons, I think this issue is fixed with PR #110. What do you think? Can we close this issue?

**Comment by jtsiddons** [comment]
@ludwiglierhammer: Do you mean PR #111?

I think it can be closed.

Thank you for adding these tests!

**Comment by ludwiglierhammer** [comment]
| @ludwiglierhammer: Do you mean PR https://github.com/glamod/cdm_reader_mapper/pull/111?

Sorry, yes I meant #111
