### ISSUE TITLE
Loss of data precision

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/cdm_reader_mapper#59]
Regarding the ``cdm_reader_mapper.cdm_mapper`` and see  ``Issue`` #8 and PR #23:

#### Current state
Whenthe [mapping to the CDM format](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/mapper.py#L336-L352), the data is stored in a ``StringIO`` buffer and then read back into a ``pd.DataFrame``.  I think this is due to memory limits and older ``pandas`` versions similar to the ``TextFileReader`` issue. The data type of the data in the ``StringIO`` buffer is **NOT** necessarily the same as the data type of the data in the ``pd.DataFrame``. [Setting the data type](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/mapper.py#L348) of the ``pd.DataFrame`` does not solve this issue. I did some tests with and without setting the data type. In this process there is a loss off data precision. I do not know why reading from a ``StringIO`` buffer leads to this loss. 

#### Example
The latitude in [the input data](https://github.com/glamod/cdm-testdata/blob/main/imma1_714/input/063-714_2010-07-01_subset.imma) is ``8838``.  The ``mdf_reader`` converts this value into the ``float16`` value ``88.3750``.  After mapping the data and reading it back, we get ``88.40``. The reqested number of digtis in the ``cdm_mapper`` psv output files is 4. Thus, we get ``88.4000`` in [those files](https://github.com/glamod/cdm-testdata/blob/main/imma1_714/cdm_tables/header-063-714_2010-07-01_subset.psv). 

#### Crazy issue
Since ``cdm_reader_mapper`` converts data from ``pd.DataFrame``s into ``TextFileReader`` objects and ``StringIO`` buffer and vice versa, mainly for memory limit reasons, the input data is manipulated in a way that we may not want.

#### Question to @aanderss, @rcornes, @lizkent and @jtsiddons   
Do we want this loss of data precision in our data? If not, I do not think I can fix this issue until the next release.

**Comment by jtsiddons** [comment]
Could we use Float32 instead of Float16? I think 8838 would go to 88.3800 in this case.

**Comment by ludwiglierhammer** [comment]
> Could we use Float32 instead of Float16? I think 8838 would go to 88.3800 in this case.

I am searchin for the first occurance of the problem. I could't find where the data type of ``longitude`` is set to ``float16`` 😕

**Comment by ludwiglierhammer** [comment]
The issue begins in ``mdf_reader``. At the beginning each element is read as an ``object``. Afterwards this ``object`` is [converted](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/utils/converters.py) into the requested data type. For our ``latitude``  example this is ``float32`` ([object_to_numeric](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/utils/converters.py#L44-L78
)). This is the code snippet:
```
        scale = scale if scale else self.numeric_scale
        offset = offset if offset else self.numeric_offset
        if data.dtype == "object":
            data = self.to_numeric(data)

        data = offset + data * scale
        return pd.Series(data, dtype=self.dtype)
```
* At the beginning ``data`` is an ``object``: ``8838``
* ``scale`` is a ``float64``: `0.01` (this is the default float type)
* ``offset`` is a ``float64`` too: `0.01` 
* ``self.dtype`` is ``float32``
* data = [self.to_numeric(data)](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/utils/converters.py#L26-L42) -> ``data`` turns into an ``int64`` (this is the default integer type): ``8838``
* data = offset + data * scale -> data turns into a ``float64``: ``88.38``
* pd.Series(data, dtype=self.dtype) -> ``data`` turns into a ``float32``: ``88.379997``

Here you can see the first "strange" thing.

After some data type conversions more the value is a ``float64``: ``88.379997``
In the [ouput file](https://github.com/glamod/cdm-testdata/blob/main/imma1_714/output/data_063-714_2010-07-01_subset.csv) (of the ``mdf_reader``) on disk it is ``88.37999725341797``.

😵 

Do we really need all those data type conversions?
What is the value we expect in both ``mdf_reader`` and ``cdm_mapper`` ouput files?

**Comment by ludwiglierhammer** [comment]
If I set requested data type to ``float``, the output is ``float64``: ``88.38``.
The tests works with both the old expected testing values (``88.37999725341797``) and the new ones (``88.38``).
For python ``float64`` ``88.38`` seems to be the same as ``float64`` ``88.37999725341797``.
I would suggest using ``float`` instead of ``float32``. Then we won't get digits in the output that are not in the ``imma1`` input. ``88.37999725341797`` turns into ``88.38`` in the ``mdf_reader`` ouput. This seems better to me to be better than before, or are there any reasons why we have this long digits number.

**Comment by jtsiddons** [comment]
Setting the latitude type to be float16 in the schema gives me 88.375 in the mdf_reader output file

**Comment by ludwiglierhammer** [comment]
In my view the mdf_reader ouput values should be as similar as possible to the input. 
``8838`` -> ``88.38`` and not ``88.375`` or anything else containing digits that are not in the inputs, isn't it?

**Comment by jtsiddons** [comment]
Some schema have a `decimal_places` field, I can't find anything in the `mdf_reader` module that references this field. Could we use the value from this field to `round` these values?

e.g: https://github.com/glamod/cdm_reader_mapper/blob/8e4e8422d315d84be85831016d25562819a1f483/cdm_reader_mapper/mdf_reader/schema/imma1.json#L67-L76

**Comment by jtsiddons** [comment]
However we may still get extraneous digits...

```
>>> s = pd.Series([1012, 2249, 8838])
>>> (s/100).astype('float32').round(2)
0    10.120000
1    22.490000
2    88.379997
dtype: float32
```

**Comment by aanderss** [comment]
Output should of course be similar to the input. That is why scale and offset are used in the input data and values are stored as integers. Type castings and conversions should be avoided and it is a good idea to reduce them.

The [decimal](https://docs.python.org/3/library/decimal.html) module provides some of the capabilities we need here.

**Comment by ludwiglierhammer** [comment]
> Some schema have a `decimal_places` field, I can't find anything in the `mdf_reader` module that references this field. Could we use the value from this field to `round` these values?
> 
> e.g:
> 
> https://github.com/glamod/cdm_reader_mapper/blob/8e4e8422d315d84be85831016d25562819a1f483/cdm_reader_mapper/mdf_reader/schema/imma1.json#L67-L76

That is good to know.

**Comment by ludwiglierhammer** [comment]
I created I new PR #60.

**Comment by ludwiglierhammer** [comment]
> Some schema have a `decimal_places` field, I can't find anything in the `mdf_reader` module that references this field. Could we use the value from this field to `round` these values?
> 
> e.g:
> 
> https://github.com/glamod/cdm_reader_mapper/blob/8e4e8422d315d84be85831016d25562819a1f483/cdm_reader_mapper/mdf_reader/schema/imma1.json#L67-L76

I have removed these lines in PR #60 as they are not used.

**Edit:** I have withdrawed these commits. The decimal_places are written to ``MDFFileReader`` object which is an input for the ``cdm_mapper``. So ``decimal_places`` from ``mdf_reader`` are used in ``cdm_mapper``. Maybe we should transfer ``decimal_places`` from ``mdf_reader`` to ``cdm_mapper`` in a further PR.

**Comment by ludwiglierhammer** [comment]
> However we may still get extraneous digits...
> 
> ```
> >>> s = pd.Series([1012, 2249, 8838])
> >>> (s/100).astype('float32').round(2)
> 0    10.120000
> 1    22.490000
> 2    88.379997
> dtype: float32
> ```

When we use default integer and float types we don't need any rounding.

**Comment by ludwiglierhammer** [comment]
Luckily, we do not need to touch the ``TextFileReader`` issue to solve this issuue.
Using default ``int`` and ``float`` types seems to be enough.

**Comment by ludwiglierhammer** [comment]
#60 merged
Done.
