### ISSUE TITLE
decimal_places: from ``mdf_reader`` to ``cdm_mapper ``

### ISSUE THREAD

**Issue by ludwiglierhammer** [glamod/cdm_reader_mapper#66]
Move information about decimal_places from ``mdf_reader`` to ``cdm_mapper`` as they are only used in ``cdm_mapper``.

**Comment by ludwiglierhammer** [comment]
Hi @aanderss, I found some inconsistencies in the decimal places. Could you please takea look at the list below?

#### 701/721

The precision of ``original_value`` in the [output data](https://github.com/glamod/cdm-testdata/blob/main/imma1_721/cdm_tables/observations-at-125-721_1862-06-01_subset.psv) is not equal to the precision in the [input data](https://github.com/glamod/cdm-testdata/blob/main/imma1_721/input/125-721_1862-06-01_subset.imma). There are five decimal places in the output and none in the input. ``original_value`` and ``observation_value`` are not similar.

e.g. (721): 
* ``(c99_data, air_temperature)`` is ``53`` -> ``original_value`` is ``53.00000``
* ``core, AT`` is ``44`` -> ``observation_value`` is ``277.55``

✔️ 

#### 702

In the [observations tables](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/tables/icoads_r3000_d702/observations-at.json) there are no ``original_value``s defined. Should we set them to ``observation_value`` like [here](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/tables/icoads_r3000/observations-at.json#L101-L104)?

#### 714

In the [observations-wd table](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/tables/icoads_r3000_d714/observations-wd.json#L106) ``decimal_places`` of ``original_value`` is set to ``0``.  Should we change the value to ``2`` like in the [input data](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1_d714.json#L2401)?

✔️ 

#### 730

empty ``observations_tables``s: ``AT``, ``SST``, ``DPT`` and ``SLP``. Given decimal places: 5
Should we set this to ``2``?

✔️ -> according to backup files on rcl.

#### 781

In the [observations-slp table](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/tables/icoads_r3000_d781/observations-slp.json#L107) ``decimal_places`` of ``original_value`` is set to ``2``. Should we change the value to ``1`` like in the [input data](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1_d781.json#L2519) (same with ``observations-ws``).

✔️ 

#### C-RAID

In the header table ``decimal_places`` of ``height_of_station_above_local_ground``, ``height_of_station_above_sea_level`` and ``report_time_accuracy`` are not set. If ``decimal_places`` are not set, they will be automatically set to ``5``. Should we set them equal to [here](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/tables/icoads_r3000/header.json)(``1``, ``1``, ``0``)

✔️

**Comment by ludwiglierhammer** [comment]
> #### 702
> In the [observations tables](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/tables/icoads_r3000_d702/observations-at.json) there are no `original_value`s defined. Should we set them to `observation_value` like [here](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/cdm_mapper/tables/icoads_r3000/observations-at.json#L101-L104)?
> 
``original_units`` is taken from [``c99_data`` attachment](https://github.com/glamod/cdm_reader_mapper/blob/main/cdm_reader_mapper/mdf_reader/schema/imma1_d702.json).
This attachment does **NOT** include any elements for ``original_value``. Thus, ``original_value`` is not defined in den ``cdm_mapper``.

@aanderss: Should we leave it as it is or take ``core`` elements for both ``original_value`` and ``original_unit`` as in the example above?

**Comment by aanderss** [comment]
This should be handled in a consistent way. if we take units from c99 attachment then the value needs to be read from there, too. Otherwise the conversion_method may be not consistent with the vales in the tables.

In this case the original_value is read from core and the original_units should be taken from core as well.

**Comment by ludwiglierhammer** [comment]
@aanderss: Just for clearification:

In this case, ``original_units`` is taken from the  ``c99_data`` attachment for observation tables ``AT`` and ``SLP``.
Because there are no values for air_temperature and sea_level_pressurein this attachment, ``original_value``is not set.
For the other observation tables, ``original_value`` is taken from ``core``and ``original_units`` is defined in the mapping json file.

For all observation tables, ``observation_value`` is taken from ``core`` and ``original_units` is defined in the mapping json files.

Question: Should ``original_value``be taken from ``core`` for observation tables ``AT`` and ``SLP`` and ``original_units`` be defined in the mapping json files, as is the case for the other observation tables?

**Comment by ludwiglierhammer** [comment]
For now, we leave it as it is.
Further discussions in #72.
